<a href="https://colab.research.google.com/github/lkssraw-7/corinthians-dahsboard/blob/main/corinthians_tratamento.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [48]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

In [49]:
from google.colab import files
arquivos = files.upload()

Saving campeonato-brasileiro-cartoes.csv to campeonato-brasileiro-cartoes (2).csv
Saving campeonato-brasileiro-estatisticas-full.csv to campeonato-brasileiro-estatisticas-full (2).csv
Saving campeonato-brasileiro-full.csv to campeonato-brasileiro-full (2).csv
Saving campeonato-brasileiro-gols.csv to campeonato-brasileiro-gols (2).csv

In [50]:
partidas = pd.read_csv('campeonato-brasileiro-full.csv')
estatic = pd.read_csv('campeonato-brasileiro-estatisticas-full.csv')
cartao = pd.read_csv('campeonato-brasileiro-cartoes.csv')
gols = pd.read_csv('campeonato-brasileiro-gols.csv')

In [51]:
print(partidas.shape)
print(estatic.shape)
print(cartao.shape)
print(gols.shape)

(9165, 17)
(18330, 13)
(20953, 8)
(10820, 6)

In [52]:
print('PARTIDAS')
display(partidas.head())
print(partidas.columns.tolist())

PARTIDAS

,ID,rodata,data,hora,mandante,visitante,formacao_mandante,formacao_visitante,tecnico_mandante,tecnico_visitante,vencedor,arena,mandante_Placar,visitante_Placar,mandante_Estado,visitante_Estado,arrecadacao
0,1,1,29/03/2003,16:00,Guarani,Vasco,NaN,NaN,NaN,NaN,Guarani,Brinco de Ouro,4,2,SP,RJ,NaN
1,2,1,29/03/2003,16:00,Athletico-PR,Gremio,NaN,NaN,NaN,NaN,Athletico-PR,Arena da Baixada,2,0,PR,RS,NaN
2,3,1,30/03/2003,16:00,Flamengo,Coritiba,NaN,NaN,NaN,NaN,-,Maracanã,1,1,RJ,PR,NaN
3,4,1,30/03/2003,16:00,Goias,Paysandu,NaN,NaN,NaN,NaN,-,Serra Dourada,2,2,GO,PA,NaN
4,5,1,30/03/2003,16:00,Internacional,Ponte Preta,NaN,NaN,NaN,NaN,-,Beira Rio,1,1,RS,SP,NaN

['ID', 'rodata', 'data', 'hora', 'mandante', 'visitante', 'formacao_mandante', 'formacao_visitante', 'tecnico_mandante', 'tecnico_visitante', 'vencedor', 'arena', 'mandante_Placar', 'visitante_Placar', 'mandante_Estado', 'visitante_Estado', 'arrecadacao']

In [53]:
print('\nESTATISTICA')
display(estatic.head())
print(estatic.columns.tolist())

ESTATISTICA

,partida_id,rodata,clube,chutes,chutes_no_alvo,posse_de_bola,passes,precisao_passes,faltas,cartao_amarelo,cartao_vermelho,impedimentos,escanteios
0,1,1,Vasco,0,0,NaN,0,NaN,0,0,0,0,0
1,1,1,Guarani,0,0,NaN,0,NaN,0,0,0,0,0
2,2,1,Athletico-PR,0,0,NaN,0,NaN,0,0,0,0,0
3,2,1,Gremio,0,0,NaN,0,NaN,0,0,0,0,0
4,3,1,Flamengo,0,0,NaN,0,NaN,0,0,0,0,0

['partida_id', 'rodata', 'clube', 'chutes', 'chutes_no_alvo', 'posse_de_bola', 'passes', 'precisao_passes', 'faltas', 'cartao_amarelo', 'cartao_vermelho', 'impedimentos', 'escanteios']

In [54]:
print('\nCARTÕES')
display(cartao.head())
print(cartao.columns.tolist())

CARTÕES

,partida_id,rodata,clube,cartao,atleta,num_camisa,posicao,minuto
0,4607,1,Figueirense,Amarelo,Thiago Heleno,4.0,Zagueiro,44
1,4607,1,Figueirense,Amarelo,Paulo Roberto da Silva,28.0,NaN,66
2,4608,1,Internacional,Amarelo,Juan Silveira dos Santos,4.0,Zagueiro,20
3,4608,1,Vitoria,Amarelo,Vinícius Santos Silva,NaN,NaN,82
4,4608,1,Internacional,Amarelo,Andrés D'Alessandro,10.0,Meio-campo,72

['partida_id', 'rodata', 'clube', 'cartao', 'atleta', 'num_camisa', 'posicao', 'minuto']

In [55]:
print('\nGOLS')
display(gols.head())
print(gols.columns.tolist())

GOLS

,partida_id,rodata,clube,atleta,minuto,tipo_de_gol
0,4607,1,Fluminense,Rafael Sóbis,31,NaN
1,4607,1,Fluminense,Fred,45,Penalty
2,4607,1,Fluminense,Nirley da Silva Fonseca,59,Gol Contra
3,4608,1,Internacional,Charles Aránguiz,6,NaN
4,4612,1,Cruzeiro,Marcelo Moreno,90,NaN

['partida_id', 'rodata', 'clube', 'atleta', 'minuto', 'tipo_de_gol']

In [56]:
partidas["data"] = pd.to_datetime(
    partidas["data"],
    format="%d/%m/%Y",
    errors="coerce"
)

In [57]:
partidas[['data']].head()

        data
0 2003-03-29
1 2003-03-29
2 2003-03-30
3 2003-03-30
4 2003-03-30

In [58]:
part_cor = partidas[(partidas['mandante'] =='Corinthians')|(partidas['visitante'] == 'Corinthians')].copy()
part_cor

,ID,rodata,data,hora,mandante,visitante,formacao_mandante,formacao_visitante,tecnico_mandante,tecnico_visitante,vencedor,arena,mandante_Placar,visitante_Placar,mandante_Estado,visitante_Estado,arrecadacao
11,12,1,2003-03-30,18:00,Corinthians,Atletico-MG,NaN,NaN,NaN,NaN,Atletico-MG,Pacaembu,0,3,SP,MG,NaN
17,18,2,2003-04-06,16:00,Figueirense,Corinthians,NaN,NaN,NaN,NaN,-,Orlando Scarpelli,3,3,SC,SP,NaN
28,40,3,2003-04-12,18:00,Corinthians,Paysandu,NaN,NaN,NaN,NaN,Corinthians,Pacaembu,6,1,SP,PA,NaN
43,32,4,2003-04-16,21:40,Vasco,Corinthians,NaN,NaN,NaN,NaN,-,São Januário,2,2,RJ,SP,NaN
53,53,5,2003-04-20,16:00,Internacional,Corinthians,NaN,NaN,NaN,NaN,Internacional,Beira Rio,2,1,RS,SP,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9123,9132,34,2025-11-20,19:30,Corinthians,Sao Paulo,4-4-2,3-5-2,D. Junior,H. Crespo,Corinthians,"Neo Química Arena, São Paulo",3,1,SP,SP,3539617.2
9131,9142,35,2025-11-23,20:34,Cruzeiro,Corinthians,4-2-3-1,5-3-2,T. Tite,D. Junior,Cruzeiro,"Mineirão, Belo Horizonte",3,0,MG,SP,1637835.5
9144,9155,36,2025-11-30,16:00,Corinthians,Botafogo-RJ,4-1-2-1-2,4-2-3-1,Dorival Silvestre Junior,Davide Ancelotti,-,"Neo Química Arena, São Paulo",2,2,SP,RJ,2694558.5
9149,9120,37,2025-12-03,19:03,Fortaleza,Corinthians,4-2-3-1,4-3-3,T. Carpini,D. Junior,Fortaleza,"Arena Castelão, Fortaleza",2,1,CE,SP,1433088.0
9159,9159,38,2025-12-07,16:04,Corinthians,Juventude,3-4-3,4-2-3-1,D. Junior,M. Barbieri,-,"Neo Química Arena, São Paulo",1,1,SP,RS,1888899.0

In [59]:
print('Quantidade de Partidas  - Corinthians ( entre 2003 - 2025): ',len(part_cor))

display(part_cor[['ID','data','mandante','visitante','mandante_Placar', 'visitante_Placar']].head())

Quantidade de Partidas  - Corinthians ( entre 2003 - 2025):  856

,ID,data,mandante,visitante,mandante_Placar,visitante_Placar
11,12,2003-03-30,Corinthians,Atletico-MG,0,3
17,18,2003-04-06,Figueirense,Corinthians,3,3
28,40,2003-04-12,Corinthians,Paysandu,6,1
43,32,2003-04-16,Vasco,Corinthians,2,2
53,53,2003-04-20,Internacional,Corinthians,2,1

In [60]:
ids_cor = part_cor['ID']

In [61]:
estatic_cor = estatic[(estatic['partida_id'].isin(ids_cor)) & (estatic['clube']=='Corinthians')].copy()

gols_cor = gols[(gols['partida_id'].isin(ids_cor)) & (gols['clube']=='Corinthians')].copy()

cartao_cor = cartao[(cartao['partida_id'].isin(ids_cor)) & (cartao['clube']=='Corinthians')].copy()

In [62]:
print("Partidas:", part_cor.shape)
print("Estatísticas:", estatic_cor.shape)
print("Gols:", gols_cor.shape)
print("Cartões:", cartao_cor.shape)

Partidas: (856, 17)
Estatísticas: (856, 13)
Gols: (566, 6)
Cartões: (905, 8)

In [63]:
print(
    "Partidas com estatísticas:",
    estatic_cor["partida_id"].nunique()
)

print(
    "Partidas com autores de gols:",
    gols_cor["partida_id"].nunique()
)

print(
    "Partidas com cartões registrados:",
    cartao_cor["partida_id"].nunique()
)

Partidas com estatísticas: 856
Partidas com autores de gols: 332
Partidas com cartões registrados: 372

In [64]:
part_cor['temporada'] = part_cor['data'].dt.year

jogos_finais_2020 = ((part_cor['data'].dt.year ==2021) & (part_cor['data'].dt.month <= 10))

part_cor.loc[jogos_finais_2020, 'temporada'] = 2020
part_cor[ 'temporada'] = part_cor['temporada'].astype(int)

In [65]:
part_cor.groupby('temporada').size()

temporada
2003    46
2004    46
2005    42
2006    38
2007    38
2009    38
2010    38
2011    38
2012    38
2013    38
2014    38
2015    38
2016    38
2017    38
2018    38
2019    38
2020    66
2021    10
2022    38
2023    38
2024    38
2025    38
dtype: int64

In [66]:
part_cor['local'] = np.where(part_cor['mandante'] == 'Corinthians', 'Mandante', 'Visitante')

part_cor['adversario'] = np.where(
    part_cor['mandante'] == 'Corinthians',
    part_cor['mandante_Placar'],
    part_cor['visitante_Placar']
)

part_cor['placar'] = np.where(
    part_cor['mandante'] == 'Corinthians',
    part_cor['mandante_Placar'],
    part_cor['visitante_Placar']
)

part_cor["gols_marcados"] = np.where(
    part_cor["mandante"] == "Corinthians",
    part_cor["mandante_Placar"],
    part_cor["visitante_Placar"]
)

part_cor['gols_sofridos'] = np.where(
    part_cor['mandante'] == 'Corinthians',
    part_cor['visitante_Placar'],
    part_cor['mandante_Placar']
)


part_cor['saldo_gols'] = (
    part_cor['gols_marcados'] -
    part_cor['gols_sofridos']
)

condicoes = [
    part_cor['gols_marcados'] >
    part_cor['gols_sofridos'],

    part_cor['gols_marcados'] <
    part_cor['gols_sofridos']
  ]
resultados = ['Vitoria', 'Derrota']

part_cor['resultado'] = np.select(
    condicoes,
    resultados,
    default='Empate'
)

In [67]:
part_cor['pontos'] = part_cor['resultado'].map({
    'Vitoria': 3,
    'Derrota': 0,
    'Empate': 1
})

In [68]:
part_cor['tecnico'] = np.where(
    part_cor['mandante'] == 'Corinthians',
    part_cor['tecnico_mandante'],
    part_cor['tecnico_visitante']
)

part_cor['formacao'] = np.where(
    part_cor['mandante'] == 'Corinthians',
    part_cor['formacao_mandante'],
    part_cor['formacao_visitante']
)

In [69]:
colunas_part = [
    'ID',
    'temporada',
    'rodata',
    'data',
    'hora',
    'adversario',
    'local',
    'arena',
    'gols_marcados',
    'gols_sofridos',
    'saldo_gols',
    'resultado',
    'pontos',
    'tecnico',
    'formacao',
    'arrecadacao'

]

base_part = part_cor[colunas_part].copy()

In [70]:
display(base_part.head())

,ID,temporada,rodata,data,hora,adversario,local,arena,gols_marcados,gols_sofridos,saldo_gols,resultado,pontos,tecnico,formacao,arrecadacao
11,12,2003,1,2003-03-30,18:00,0,Mandante,Pacaembu,0,3,-3,Derrota,0,NaN,NaN,NaN
17,18,2003,2,2003-04-06,16:00,3,Visitante,Orlando Scarpelli,3,3,0,Empate,1,NaN,NaN,NaN
28,40,2003,3,2003-04-12,18:00,6,Mandante,Pacaembu,6,1,5,Vitoria,3,NaN,NaN,NaN
43,32,2003,4,2003-04-16,21:40,2,Visitante,São Januário,2,2,0,Empate,1,NaN,NaN,NaN
53,53,2003,5,2003-04-20,16:00,1,Visitante,Beira Rio,1,2,-1,Derrota,0,NaN,NaN,NaN

In [71]:
resumo_geral = {
    "Jogos": len(base_part),
    "Vitórias": (base_part["resultado"] == "Vitoria").sum(),
    "Empates": (base_part["resultado"] == "Empate").sum(),
    "Derrotas": (base_part["resultado"] == "Derrota").sum(),
    "Gols marcados": base_part["gols_marcados"].sum(),
    "Gols sofridos": base_part["gols_sofridos"].sum(),
    "Pontos": base_part["pontos"].sum()
}

pd.Series(resumo_geral)

Jogos             856
Vitórias          353
Empates           251
Derrotas          252
Gols marcados    1095
Gols sofridos     924
Pontos           1310
dtype: int64

In [72]:
pontos_possiveis = len(base_part) * 3

aproveitamento = (base_part['pontos'].sum()/pontos_possiveis) *100

print(f'Aproveitamento geral: {aproveitamento:.2f}')

Aproveitamento geral: 51.01

In [73]:
display(
    base_part[
        [
            "temporada",
            "data",
            "adversario",
            "local",
            "gols_marcados",
            "gols_sofridos",
            "resultado",
            "pontos"
        ]
    ].head(10)
)

,temporada,data,adversario,local,gols_marcados,gols_sofridos,resultado,pontos
11,2003,2003-03-30,0,Mandante,0,3,Derrota,0
17,2003,2003-04-06,3,Visitante,3,3,Empate,1
28,2003,2003-04-12,6,Mandante,6,1,Vitoria,3
43,2003,2003-04-16,2,Visitante,2,2,Empate,1
53,2003,2003-04-20,1,Visitante,1,2,Derrota,0
65,2003,2003-04-27,1,Mandante,1,1,Empate,1
76,2003,2003-05-04,2,Visitante,2,1,Vitoria,3
88,2003,2003-05-10,3,Mandante,3,0,Vitoria,3
103,2003,2003-05-18,1,Visitante,1,1,Empate,1
111,2003,2003-05-24,3,Mandante,3,0,Vitoria,3

In [74]:
coluna_estat = [

    'partida_id',
    'chutes',
    'chutes_no_alvo',
    'posse_de_bola',
    'precisao_passes',
    'passes',
    'faltas',
    'cartao_amarelo',
    'cartao_vermelho',
    'impedimentos',
    'escanteios'
]

estatic_cor_limpa = estatic_cor[coluna_estat].copy()

In [75]:
colunas_percentuais = ['posse_de_bola','precisao_passes']

for coluna in colunas_percentuais:
    estatic_cor_limpa[coluna] = (estatic_cor_limpa[coluna].astype(str).str.replace('%','', regex=False)
    .str.replace(',', '.', regex=False))
    estatic_cor_limpa[coluna] = pd.to_numeric(estatic_cor_limpa[coluna], errors='coerce')


estatic_cor_limpa.dtypes

partida_id           int64
chutes               int64
chutes_no_alvo       int64
posse_de_bola      float64
precisao_passes    float64
passes               int64
faltas               int64
cartao_amarelo       int64
cartao_vermelho      int64
impedimentos         int64
escanteios           int64
dtype: object

In [76]:
estatic_cor_limpa["partida_id"].duplicated().sum()

np.int64(0)

In [77]:
base_part = base_part.merge(estatic_cor_limpa, how='left',left_on='ID', right_on='partida_id',validate='one_to_one')

base_part.drop(columns='partida_id',inplace=True)

In [78]:
print("Linhas:", base_part.shape)
print("Colunas:", base_part.columns.tolist())

Linhas: (856, 26)
Colunas: ['ID', 'temporada', 'rodata', 'data', 'hora', 'adversario', 'local', 'arena', 'gols_marcados', 'gols_sofridos', 'saldo_gols', 'resultado', 'pontos', 'tecnico', 'formacao', 'arrecadacao', 'chutes', 'chutes_no_alvo', 'posse_de_bola', 'precisao_passes', 'passes', 'faltas', 'cartao_amarelo', 'cartao_vermelho', 'impedimentos', 'escanteios']

In [79]:
display(
    base_part[
        [
            "temporada",
            "data",
            "adversario",
            "resultado",
            "gols_marcados",
            "chutes",
            "chutes_no_alvo",
            "posse_de_bola",
            "passes",
            "precisao_passes"
        ]
    ].tail(10)
)

,temporada,data,adversario,resultado,gols_marcados,chutes,chutes_no_alvo,posse_de_bola,passes,precisao_passes
846,2025,2025-10-18,1,Vitoria,1,9,1,65.0,519,92.0
847,2025,2025-10-25,1,Vitoria,1,9,4,60.0,365,90.0
848,2025,2025-11-02,2,Vitoria,2,14,4,57.0,515,92.0
849,2025,2025-11-05,1,Derrota,1,5,3,43.0,236,87.0
850,2025,2025-11-09,0,Derrota,0,15,5,77.0,655,92.0
851,2025,2025-11-20,3,Vitoria,3,13,5,47.0,308,88.0
852,2025,2025-11-23,0,Derrota,0,3,0,53.0,332,91.0
853,2025,2025-11-30,2,Empate,2,11,4,61.0,391,89.0
854,2025,2025-12-03,1,Derrota,1,20,8,70.0,476,95.0
855,2025,2025-12-07,1,Empate,1,11,6,55.0,443,90.0

In [80]:
base_part['estatisticas_disponiveis'] = (base_part['posse_de_bola'].notna()| (base_part['passes'] > 0) | (base_part['chutes']>0))

disponibilidade = (base_part.groupby('temporada').agg(partidas=('ID','count'), partida_com_estatistica=('estatisticas_disponiveis','sum')).reset_index( ))

display(disponibilidade)

    temporada  partidas  partida_com_estatistica
0        2003        46                        0
1        2004        46                        0
2        2005        42                        0
3        2006        38                        0
4        2007        38                        0
5        2009        38                        0
6        2010        38                        0
7        2011        38                        0
8        2012        38                        0
9        2013        38                        0
10       2014        38                        2
11       2015        38                       38
12       2016        38                       38
13       2017        38                       38
14       2018        38                       38
15       2019        38                       37
16       2020        66                       66
17       2021        10                       10
18       2022        38                       38
19       2023        38                       38
20       2024        38                        0
21       2025        38                       38

In [81]:
#aproveitamento por partida
base_part['aproveitamneto_partida'] = (base_part['pontos']/3)*100

In [82]:
base_part["precisao_finalizacao"] = np.where(
    base_part["chutes"] > 0,
    (
        base_part["chutes_no_alvo"] /
        base_part["chutes"]
    ) * 100,
    np.nan
)

In [83]:
base_part['conversao_chutes'] = np.where(
    base_part['chutes'] > 0,
    (
        base_part['gols_marcados'] /
        base_part['chutes']
    )*100,
    np.nan
)

In [84]:
base_part["conversao_no_alvo"] = np.where(
    base_part["chutes_no_alvo"] > 0,
    (
        base_part["gols_marcados"] /
        base_part["chutes_no_alvo"]
    ) * 100,
    np.nan
)

In [85]:
resumo_temporadas = (
    base_part
    .groupby("temporada")
    .agg(
        jogos=("ID", "count"),
        pontos=("pontos", "sum"),
        gols_marcados=("gols_marcados", "sum"),
        gols_sofridos=("gols_sofridos", "sum"),
        media_chutes=("chutes", "mean"),
        media_posse=("posse_de_bola", "mean"),
        media_passes=("passes", "mean")
    )
    .reset_index()
)

resumo_temporadas["aproveitamento"] = (
    resumo_temporadas["pontos"] /
    (resumo_temporadas["jogos"] * 3)
) * 100

display(resumo_temporadas.tail(10).round(2))

,temporada,jogos,pontos,gols_marcados,gols_sofridos,media_chutes,media_posse,media_passes,aproveitamento
12,2016,38,55,48,42,12.76,56.18,496.37,48.25
13,2017,38,72,50,30,12.63,54.61,504.18,63.16
14,2018,38,44,34,35,10.58,55.11,493.45,38.60
15,2019,38,56,42,34,12.66,51.57,424.58,49.12
16,2020,66,92,75,71,11.59,51.18,470.24,46.46
17,2021,10,16,10,10,12.30,61.30,568.30,53.33
18,2022,38,65,44,36,11.82,55.11,499.18,57.02
19,2023,38,50,47,48,12.16,48.55,457.39,43.86
20,2024,38,56,54,45,0.00,NaN,0.00,49.12
21,2025,38,47,42,47,10.37,55.03,429.89,41.23

In [86]:
base_gols = gols[
    (gols['partida_id'].isin(base_part['ID'])) &
    (gols['clube'] == 'Corinthians')
].copy()

In [87]:
print(base_gols.shape)
display(base_gols.head())

(566, 6)

,partida_id,rodata,clube,atleta,minuto,tipo_de_gol
27,4621,2,Corinthians,Carlos Gilberto do Nascimento Silva,80,NaN
28,4621,2,Corinthians,Guilherme dos Santos Torres,9,NaN
61,4635,3,Corinthians,Paolo Guerrero,78,NaN
83,4643,4,Corinthians,Fagner,49,NaN
124,4661,6,Corinthians,Jadson,59,Penalty

In [88]:
info_partidas = base_part[
    [
        "ID",
        "temporada",
        "data",
        "adversario",
        "local",
        "resultado"
    ]
].copy()

In [89]:
base_gols = base_gols.merge(
    info_partidas,
    how="left",
    left_on="partida_id",
    right_on="ID",
    validate="many_to_one"
)

In [95]:
base_gols[ 'minuto_original'] = base_gols['minuto'].astype(str)

def converter_minuto(minuto):
  if pd.isna(minuto):
    return np.nan

  minuto = str(minuto).strip()

  if minuto.lower() == 'nan':
    return np.nan

  if '+' in minuto:
    partes = minuto.split('+')

    try:
      return int (partes[0]) + int(partes[1])
    except:
      return np.nan
  try:
    return int(float(minuto))

  except:
    return np.nan

In [96]:
    base_gols['minuto_numerico'] = (
        base_gols['minuto']
        .apply(converter_minuto)
    )

In [97]:
faixas = [ 0, 15 , 30, 45, 60,75 ,90, float('inf')]

nomes_faixas = [
    '0-15',
    '16-30',
    '31-45',
    '46-60',
    '61-75',
    '76-90',
    '90+'
]

base_gols["intervalo_gol"] = pd.cut(

    base_gols["minuto_numerico"],

    bins=faixas,

    labels=nomes_faixas,

    include_lowest=True

)

base_gols['intervalo_gol'].value_counts().sort_index()

intervalo_gol
0-15      61
16-30     90
31-45     71
46-60    109
61-75     84
76-90    112
90+       39
Name: count, dtype: int64

In [98]:
base_gols['tipo_de_gol'] = (
    base_gols['tipo_de_gol']
    .fillna('Gol normal')
    .replace({
        'Penalty': 'Pênalti',
        'Own-goal': 'Gol contra'
    })
    )

In [101]:
base_gols['tipo_de_gol'].value_counts()

tipo_de_gol
Gol normal    503
Pênalti        49
Gol Contra     14
Name: count, dtype: int64

In [102]:
base_cartoes = cartao[
    (cartao['partida_id'].isin(base_part["ID"])) &
    (cartao['clube'] == 'Corinthians')
].copy()

print(base_cartoes.shape)
display(base_cartoes.head())

(905, 8)

,partida_id,rodata,clube,cartao,atleta,num_camisa,posicao,minuto
62,4621,2,Corinthians,Amarelo,Paolo Guerrero,9.0,Atacante,7
64,4621,2,Corinthians,Amarelo,Ralf de Souza Teles,5.0,Meio-campo,26
124,4635,3,Corinthians,Amarelo,Fagner,23.0,Zagueiro,43
125,4635,3,Corinthians,Amarelo,Romarinho,31.0,Atacante,15
128,4635,3,Corinthians,Amarelo,Guilherme dos Santos Torres,19.0,Meio-campo,25

In [113]:
base_cartoes['cartao'].value_counts(dropna=False)

cartao
Amarelo     866
Vermelho     39
Name: count, dtype: int64

In [115]:
# Recria a base de cartões a partir da tabela original
base_cartoes = cartao[
    (cartao["partida_id"].isin(base_part["ID"])) &
    (cartao["clube"] == "Corinthians")
].copy()

# Informações das partidas
info_partidas = base_part[
    [
        "ID",
        "temporada",
        "data",
        "adversario",
        "local",
        "resultado"
    ]
].copy()

# Adiciona os dados da partida em cada cartão
base_cartoes = base_cartoes.merge(
    info_partidas,
    how="left",
    left_on="partida_id",
    right_on="ID",
    validate="many_to_one"
)

# Remove o ID duplicado
base_cartoes.drop(columns="ID", inplace=True)

In [116]:
def classificar_cartao(cartao):
  cartao = str(cartao).lower()

  if 'vermelho' in cartao:
    return 'Vermelho'

  if 'amarelo' in cartao:
    return 'Amarelo'

  return 'Outro'

base_cartoes["tipo_cartao"] = (

    base_cartoes["cartao"]

    .apply(classificar_cartao)

)

base_cartoes["tipo_cartao"].value_counts()

tipo_cartao
Amarelo     866
Vermelho     39
Name: count, dtype: int64

In [117]:
print("Partidas:", base_part.shape)

print("Gols:", base_gols.shape)

print("Cartões:", base_cartoes.shape)

Partidas: (856, 31)
Gols: (566, 15)
Cartões: (905, 14)

In [118]:
print(

    "Gols sem temporada:",

    base_gols["temporada"].isna().sum()

)

print(

    "Cartões sem temporada:",

    base_cartoes["temporada"].isna().sum()

)

Gols sem temporada: 0
Cartões sem temporada: 0

In [120]:
print("=== TAMANHO DAS BASES ===")
print("Partidas:", base_part.shape)
print("Gols:", base_gols.shape)
print("Cartões:", base_cartoes.shape)

print("\n=== DUPLICAÇÕES ===")
print("Partidas duplicadas:", base_part["ID"].duplicated().sum())
print("Gols duplicados:", base_gols.duplicated().sum())
print("Cartões duplicados:", base_cartoes.duplicated().sum())

print("\n=== VALORES AUSENTES IMPORTANTES ===")
print("Partidas sem temporada:", base_part["temporada"].isna().sum())
print("Partidas sem adversário:", base_part["adversario"].isna().sum())
print("Gols sem temporada:", base_gols["temporada"].isna().sum())
print("Cartões sem temporada:", base_cartoes["temporada"].isna().sum())

=== TAMANHO DAS BASES ===
Partidas: (856, 31)
Gols: (566, 15)
Cartões: (905, 14)

=== DUPLICAÇÕES ===
Partidas duplicadas: 0
Gols duplicados: 0
Cartões duplicados: 0

=== VALORES AUSENTES IMPORTANTES ===
Partidas sem temporada: 0
Partidas sem adversário: 0
Gols sem temporada: 0
Cartões sem temporada: 0

In [121]:
gols_sem_partida = (
    ~base_gols["partida_id"].isin(base_part["ID"])
).sum()

cartoes_sem_partida = (
    ~base_cartoes["partida_id"].isin(base_part["ID"])
).sum()

print("Gols sem partida correspondente:", gols_sem_partida)
print("Cartões sem partida correspondente:", cartoes_sem_partida)

Gols sem partida correspondente: 0
Cartões sem partida correspondente: 0

In [122]:
print(base_part["resultado"].value_counts())

print("\nTotal de jogos:")
print(base_part["resultado"].value_counts().sum())

resultado
Vitoria    353
Derrota    252
Empate     251
Name: count, dtype: int64

Total de jogos:
856

In [123]:
display(
    base_part
    .groupby("temporada")
    .agg(
        jogos=("ID", "count"),
        pontos=("pontos", "sum"),
        gols_marcados=("gols_marcados", "sum"),
        gols_sofridos=("gols_sofridos", "sum")
    )
    .reset_index()
)

    temporada  jogos  pontos  gols_marcados  gols_sofridos
0        2003     46      57             61             63
1        2004     46      74             54             54
2        2005     42      81             87             59
3        2006     38      53             41             46
4        2007     38      44             40             50
5        2009     38      52             50             54
6        2010     38      68             65             41
7        2011     38      71             53             36
8        2012     38      57             51             39
9        2013     38      50             27             22
10       2014     38      69             49             31
11       2015     38      81             71             31
12       2016     38      55             48             42
13       2017     38      72             50             30
14       2018     38      44             34             35
15       2019     38      56             42             34
16       2020     66      92             75             71
17       2021     10      16             10             10
18       2022     38      65             44             36
19       2023     38      50             47             48
20       2024     38      56             54             45
21       2025     38      47             42             47

In [124]:
base_part.to_csv(
    "partidas_corinthians.csv",
    index=False,
    encoding="utf-8-sig"
)

base_gols.to_csv(
    "gols_corinthians.csv",
    index=False,
    encoding="utf-8-sig"
)

base_cartoes.to_csv(
    "cartoes_corinthians.csv",
    index=False,
    encoding="utf-8-sig"
)

In [125]:
from google.colab import files

files.download("partidas_corinthians.csv")
files.download("gols_corinthians.csv")
files.download("cartoes_corinthians.csv")